# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_delaunay <- function(points) {
    .Call(`_RCDT_Rcpp_delaunay`, points)
}

Rcpp_constrained_delaunay <- function(points, edges) {
    .Call(`_RCDT_Rcpp_constrained_delaunay`, points, edges)
}

